/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module async_fifo(wclk, wrst_n, wr_en, wdata, wfull, rclk, rrst_n, rd_en, rdata, rempty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire [4:0] _341_;
  wire [4:0] _342_;
  wire [4:0] _343_;
  wire [4:0] _344_;
  wire [7:0] _345_;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  wire [3:0] raddr;
  wire [4:0] rbin;
  input rclk;
  wire rclk;
  input rd_en;
  wire rd_en;
  output [7:0] rdata;
  reg [7:0] rdata;
  output rempty;
  wire rempty;
  reg [4:0] rptr_gray;
  wire [4:0] rptr_sync1;
  wire [4:0] rptr_sync2;
  input rrst_n;
  wire rrst_n;
  wire [3:0] waddr;
  wire [4:0] wbin;
  input wclk;
  wire wclk;
  input [7:0] wdata;
  wire [7:0] wdata;
  output wfull;
  wire wfull;
  reg [4:0] wptr_gray;
  reg [4:0] wptr_sync1;
  reg [4:0] wptr_sync2;
  input wr_en;
  wire wr_en;
  input wrst_n;
  wire wrst_n;
  assign _341_[0] = ~wbin[0];
  assign _343_[0] = ~rbin[0];
  assign _026_ = wptr_gray[1] | wptr_gray[0];
  assign _027_ = wptr_gray[2] | ~(wptr_gray[3]);
  assign _028_ = _027_ | _026_;
  assign wfull = wptr_gray[4] & ~(_028_);
  assign _024_ = wr_en & ~(wfull);
  assign _029_ = _024_ & wrst_n;
  assign _030_ = wbin[1] | ~(wbin[0]);
  assign _031_ = wbin[3] & wbin[2];
  assign _032_ = _030_ | ~(_031_);
  assign _002_ = _029_ & ~(_032_);
  assign _033_ = wbin[1] | wbin[0];
  assign _034_ = _033_ | ~(_031_);
  assign _003_ = _029_ & ~(_034_);
  assign _035_ = wbin[3] | wbin[2];
  assign _036_ = _035_ | _033_;
  assign _015_ = _029_ & ~(_036_);
  assign _037_ = _035_ | _030_;
  assign _014_ = _029_ & ~(_037_);
  assign _038_ = wbin[0] | ~(wbin[1]);
  assign _039_ = _038_ | _035_;
  assign _013_ = _029_ & ~(_039_);
  assign _040_ = ~(wbin[1] & wbin[0]);
  assign _041_ = _040_ | _035_;
  assign _012_ = _029_ & ~(_041_);
  assign _042_ = wbin[3] | ~(wbin[2]);
  assign _043_ = _042_ | _033_;
  assign _011_ = _029_ & ~(_043_);
  assign _044_ = _042_ | _030_;
  assign _010_ = _029_ & ~(_044_);
  assign _045_ = _042_ | _038_;
  assign _009_ = _029_ & ~(_045_);
  assign _046_ = _042_ | _040_;
  assign _008_ = _029_ & ~(_046_);
  assign _047_ = wbin[2] | ~(wbin[3]);
  assign _048_ = _047_ | _033_;
  assign _007_ = _029_ & ~(_048_);
  assign _049_ = _047_ | _030_;
  assign _006_ = _029_ & ~(_049_);
  assign _050_ = _047_ | _038_;
  assign _005_ = _029_ & ~(_050_);
  assign _051_ = _031_ & ~(_040_);
  assign _000_ = _051_ & _029_;
  assign _052_ = _047_ | _040_;
  assign _004_ = _029_ & ~(_052_);
  assign _053_ = _038_ | ~(_031_);
  assign _001_ = _029_ & ~(_053_);
  assign _054_ = ~(wptr_sync2[0] ^ rptr_gray[0]);
  assign _055_ = wptr_sync2[1] ^ rptr_gray[1];
  assign _056_ = _054_ & ~(_055_);
  assign _057_ = wptr_sync2[2] ^ rptr_gray[2];
  assign _058_ = wptr_sync2[3] ^ rptr_gray[3];
  assign _059_ = _058_ | _057_;
  assign _060_ = _056_ & ~(_059_);
  assign _061_ = wptr_sync2[4] ^ rptr_gray[4];
  assign rempty = _060_ & ~(_061_);
  assign _025_ = rd_en & ~(rempty);
  assign _062_ = rbin[1] & rbin[0];
  assign _063_ = ~(rbin[3] & rbin[2]);
  assign _064_ = _063_ | ~(_062_);
  assign _065_ = rbin[0] | ~(rbin[1]);
  assign _066_ = _065_ | _063_;
  assign _067_ = _066_ & _064_;
  assign _068_ = rbin[1] | ~(rbin[0]);
  assign _069_ = _068_ | _063_;
  assign _070_ = rbin[1] | rbin[0];
  assign _071_ = _070_ | _063_;
  assign _072_ = ~(_071_ & _069_);
  assign _073_ = _067_ & ~(_072_);
  assign _074_ = rbin[2] | ~(rbin[3]);
  assign _075_ = _074_ | ~(_062_);
  assign _076_ = _074_ | _065_;
  assign _077_ = ~(_076_ & _075_);
  assign _078_ = _074_ | _068_;
  assign _079_ = _074_ | _070_;
  assign _080_ = ~(_079_ & _078_);
  assign _081_ = _080_ | _077_;
  assign _082_ = _073_ & ~(_081_);
  assign _083_ = rbin[3] | ~(rbin[2]);
  assign _084_ = _083_ | ~(_062_);
  assign _085_ = _083_ | _065_;
  assign _086_ = ~(_085_ & _084_);
  assign _087_ = _083_ | _068_;
  assign _088_ = _083_ | _070_;
  assign _089_ = ~(_088_ & _087_);
  assign _090_ = _089_ | _086_;
  assign _091_ = rbin[3] | rbin[2];
  assign _092_ = _091_ | _068_;
  assign _093_ = _091_ | ~(_062_);
  assign _094_ = _091_ | _065_;
  assign _095_ = ~(_094_ & _093_);
  assign _096_ = _095_ | ~(_092_);
  assign _097_ = _096_ | _090_;
  assign _098_ = _082_ & ~(_097_);
  assign _099_ = \mem[15] [0] & ~(_064_);
  assign _100_ = \mem[14] [0] & ~(_066_);
  assign _101_ = _100_ | _099_;
  assign _102_ = \mem[13] [0] & ~(_069_);
  assign _103_ = \mem[12] [0] & ~(_071_);
  assign _104_ = _103_ | _102_;
  assign _105_ = _104_ | _101_;
  assign _106_ = \mem[11] [0] & ~(_075_);
  assign _107_ = \mem[10] [0] & ~(_076_);
  assign _108_ = _107_ | _106_;
  assign _109_ = \mem[9] [0] & ~(_078_);
  assign _110_ = \mem[8] [0] & ~(_079_);
  assign _111_ = _110_ | _109_;
  assign _112_ = _111_ | _108_;
  assign _113_ = _112_ | _105_;
  assign _114_ = \mem[7] [0] & ~(_084_);
  assign _115_ = \mem[6] [0] & ~(_085_);
  assign _116_ = _115_ | _114_;
  assign _117_ = \mem[5] [0] & ~(_087_);
  assign _118_ = \mem[4] [0] & ~(_088_);
  assign _119_ = _118_ | _117_;
  assign _120_ = _119_ | _116_;
  assign _121_ = \mem[3] [0] & ~(_093_);
  assign _122_ = \mem[2] [0] & ~(_094_);
  assign _123_ = _122_ | _121_;
  assign _124_ = \mem[1] [0] & ~(_092_);
  assign _125_ = _124_ | _123_;
  assign _126_ = _125_ | _120_;
  assign _127_ = _126_ | _113_;
  assign _345_[0] = _098_ ? \mem[0] [0] : _127_;
  assign _128_ = \mem[15] [1] & ~(_064_);
  assign _129_ = \mem[14] [1] & ~(_066_);
  assign _130_ = _129_ | _128_;
  assign _131_ = \mem[13] [1] & ~(_069_);
  assign _132_ = \mem[12] [1] & ~(_071_);
  assign _133_ = _132_ | _131_;
  assign _134_ = _133_ | _130_;
  assign _135_ = \mem[11] [1] & ~(_075_);
  assign _136_ = \mem[10] [1] & ~(_076_);
  assign _137_ = _136_ | _135_;
  assign _138_ = \mem[9] [1] & ~(_078_);
  assign _139_ = \mem[8] [1] & ~(_079_);
  assign _140_ = _139_ | _138_;
  assign _141_ = _140_ | _137_;
  assign _142_ = _141_ | _134_;
  assign _143_ = \mem[7] [1] & ~(_084_);
  assign _144_ = \mem[6] [1] & ~(_085_);
  assign _145_ = _144_ | _143_;
  assign _146_ = \mem[5] [1] & ~(_087_);
  assign _147_ = \mem[4] [1] & ~(_088_);
  assign _148_ = _147_ | _146_;
  assign _149_ = _148_ | _145_;
  assign _150_ = \mem[3] [1] & ~(_093_);
  assign _151_ = \mem[2] [1] & ~(_094_);
  assign _152_ = _151_ | _150_;
  assign _153_ = \mem[1] [1] & ~(_092_);
  assign _154_ = _153_ | _152_;
  assign _155_ = _154_ | _149_;
  assign _156_ = _155_ | _142_;
  assign _345_[1] = _098_ ? \mem[0] [1] : _156_;
  assign _157_ = \mem[15] [2] & ~(_064_);
  assign _158_ = \mem[14] [2] & ~(_066_);
  assign _159_ = _158_ | _157_;
  assign _160_ = \mem[13] [2] & ~(_069_);
  assign _161_ = \mem[12] [2] & ~(_071_);
  assign _162_ = _161_ | _160_;
  assign _163_ = _162_ | _159_;
  assign _164_ = \mem[11] [2] & ~(_075_);
  assign _165_ = \mem[10] [2] & ~(_076_);
  assign _166_ = _165_ | _164_;
  assign _167_ = \mem[9] [2] & ~(_078_);
  assign _168_ = \mem[8] [2] & ~(_079_);
  assign _169_ = _168_ | _167_;
  assign _170_ = _169_ | _166_;
  assign _171_ = _170_ | _163_;
  assign _172_ = \mem[7] [2] & ~(_084_);
  assign _173_ = \mem[6] [2] & ~(_085_);
  assign _174_ = _173_ | _172_;
  assign _175_ = \mem[5] [2] & ~(_087_);
  assign _176_ = \mem[4] [2] & ~(_088_);
  assign _177_ = _176_ | _175_;
  assign _178_ = _177_ | _174_;
  assign _179_ = \mem[3] [2] & ~(_093_);
  assign _180_ = \mem[2] [2] & ~(_094_);
  assign _181_ = _180_ | _179_;
  assign _182_ = \mem[1] [2] & ~(_092_);
  assign _183_ = _182_ | _181_;
  assign _184_ = _183_ | _178_;
  assign _185_ = _184_ | _171_;
  assign _345_[2] = _098_ ? \mem[0] [2] : _185_;
  assign _186_ = \mem[15] [3] & ~(_064_);
  assign _187_ = \mem[14] [3] & ~(_066_);
  assign _188_ = _187_ | _186_;
  assign _189_ = \mem[13] [3] & ~(_069_);
  assign _190_ = \mem[12] [3] & ~(_071_);
  assign _191_ = _190_ | _189_;
  assign _192_ = _191_ | _188_;
  assign _193_ = \mem[11] [3] & ~(_075_);
  assign _194_ = \mem[10] [3] & ~(_076_);
  assign _195_ = _194_ | _193_;
  assign _196_ = \mem[9] [3] & ~(_078_);
  assign _197_ = \mem[8] [3] & ~(_079_);
  assign _198_ = _197_ | _196_;
  assign _199_ = _198_ | _195_;
  assign _200_ = _199_ | _192_;
  assign _201_ = \mem[7] [3] & ~(_084_);
  assign _202_ = \mem[6] [3] & ~(_085_);
  assign _203_ = _202_ | _201_;
  assign _204_ = \mem[5] [3] & ~(_087_);
  assign _205_ = \mem[4] [3] & ~(_088_);
  assign _206_ = _205_ | _204_;
  assign _207_ = _206_ | _203_;
  assign _208_ = \mem[3] [3] & ~(_093_);
  assign _209_ = \mem[2] [3] & ~(_094_);
  assign _210_ = _209_ | _208_;
  assign _211_ = \mem[1] [3] & ~(_092_);
  assign _212_ = _211_ | _210_;
  assign _213_ = _212_ | _207_;
  assign _214_ = _213_ | _200_;
  assign _345_[3] = _098_ ? \mem[0] [3] : _214_;
  assign _215_ = \mem[15] [4] & ~(_064_);
  assign _216_ = \mem[14] [4] & ~(_066_);
  assign _217_ = _216_ | _215_;
  assign _218_ = \mem[13] [4] & ~(_069_);
  assign _219_ = \mem[12] [4] & ~(_071_);
  assign _220_ = _219_ | _218_;
  assign _221_ = _220_ | _217_;
  assign _222_ = \mem[11] [4] & ~(_075_);
  assign _223_ = \mem[10] [4] & ~(_076_);
  assign _224_ = _223_ | _222_;
  assign _225_ = \mem[9] [4] & ~(_078_);
  assign _226_ = \mem[8] [4] & ~(_079_);
  assign _227_ = _226_ | _225_;
  assign _228_ = _227_ | _224_;
  assign _229_ = _228_ | _221_;
  assign _230_ = \mem[7] [4] & ~(_084_);
  assign _231_ = \mem[6] [4] & ~(_085_);
  assign _232_ = _231_ | _230_;
  assign _233_ = \mem[5] [4] & ~(_087_);
  assign _234_ = \mem[4] [4] & ~(_088_);
  assign _235_ = _234_ | _233_;
  assign _236_ = _235_ | _232_;
  assign _237_ = \mem[3] [4] & ~(_093_);
  assign _238_ = \mem[2] [4] & ~(_094_);
  assign _239_ = _238_ | _237_;
  assign _240_ = \mem[1] [4] & ~(_092_);
  assign _241_ = _240_ | _239_;
  assign _242_ = _241_ | _236_;
  assign _243_ = _242_ | _229_;
  assign _345_[4] = _098_ ? \mem[0] [4] : _243_;
  assign _244_ = \mem[15] [5] & ~(_064_);
  assign _245_ = \mem[14] [5] & ~(_066_);
  assign _246_ = _245_ | _244_;
  assign _247_ = \mem[13] [5] & ~(_069_);
  assign _248_ = \mem[12] [5] & ~(_071_);
  assign _249_ = _248_ | _247_;
  assign _250_ = _249_ | _246_;
  assign _251_ = \mem[11] [5] & ~(_075_);
  assign _252_ = \mem[10] [5] & ~(_076_);
  assign _253_ = _252_ | _251_;
  assign _254_ = \mem[9] [5] & ~(_078_);
  assign _255_ = \mem[8] [5] & ~(_079_);
  assign _256_ = _255_ | _254_;
  assign _257_ = _256_ | _253_;
  assign _258_ = _257_ | _250_;
  assign _259_ = \mem[7] [5] & ~(_084_);
  assign _260_ = \mem[6] [5] & ~(_085_);
  assign _261_ = _260_ | _259_;
  assign _262_ = \mem[5] [5] & ~(_087_);
  assign _263_ = \mem[4] [5] & ~(_088_);
  assign _264_ = _263_ | _262_;
  assign _265_ = _264_ | _261_;
  assign _266_ = \mem[3] [5] & ~(_093_);
  assign _267_ = \mem[2] [5] & ~(_094_);
  assign _268_ = _267_ | _266_;
  assign _269_ = \mem[1] [5] & ~(_092_);
  assign _270_ = _269_ | _268_;
  assign _271_ = _270_ | _265_;
  assign _272_ = _271_ | _258_;
  assign _345_[5] = _098_ ? \mem[0] [5] : _272_;
  assign _273_ = \mem[15] [6] & ~(_064_);
  assign _274_ = \mem[14] [6] & ~(_066_);
  assign _275_ = _274_ | _273_;
  assign _276_ = \mem[13] [6] & ~(_069_);
  assign _277_ = \mem[12] [6] & ~(_071_);
  assign _278_ = _277_ | _276_;
  assign _279_ = _278_ | _275_;
  assign _280_ = \mem[11] [6] & ~(_075_);
  assign _281_ = \mem[10] [6] & ~(_076_);
  assign _282_ = _281_ | _280_;
  assign _283_ = \mem[9] [6] & ~(_078_);
  assign _284_ = \mem[8] [6] & ~(_079_);
  assign _285_ = _284_ | _283_;
  assign _286_ = _285_ | _282_;
  assign _287_ = _286_ | _279_;
  assign _288_ = \mem[7] [6] & ~(_084_);
  assign _289_ = \mem[6] [6] & ~(_085_);
  assign _290_ = _289_ | _288_;
  assign _291_ = \mem[5] [6] & ~(_087_);
  assign _292_ = \mem[4] [6] & ~(_088_);
  assign _293_ = _292_ | _291_;
  assign _294_ = _293_ | _290_;
  assign _295_ = \mem[3] [6] & ~(_093_);
  assign _296_ = \mem[2] [6] & ~(_094_);
  assign _297_ = _296_ | _295_;
  assign _298_ = \mem[1] [6] & ~(_092_);
  assign _299_ = _298_ | _297_;
  assign _300_ = _299_ | _294_;
  assign _301_ = _300_ | _287_;
  assign _345_[6] = _098_ ? \mem[0] [6] : _301_;
  assign _302_ = \mem[15] [7] & ~(_064_);
  assign _303_ = \mem[14] [7] & ~(_066_);
  assign _304_ = _303_ | _302_;
  assign _305_ = \mem[13] [7] & ~(_069_);
  assign _306_ = \mem[12] [7] & ~(_071_);
  assign _307_ = _306_ | _305_;
  assign _308_ = _307_ | _304_;
  assign _309_ = \mem[11] [7] & ~(_075_);
  assign _310_ = \mem[10] [7] & ~(_076_);
  assign _311_ = _310_ | _309_;
  assign _312_ = \mem[9] [7] & ~(_078_);
  assign _313_ = \mem[8] [7] & ~(_079_);
  assign _314_ = _313_ | _312_;
  assign _315_ = _314_ | _311_;
  assign _316_ = _315_ | _308_;
  assign _317_ = \mem[7] [7] & ~(_084_);
  assign _318_ = \mem[6] [7] & ~(_085_);
  assign _319_ = _318_ | _317_;
  assign _320_ = \mem[5] [7] & ~(_087_);
  assign _321_ = \mem[4] [7] & ~(_088_);
  assign _322_ = _321_ | _320_;
  assign _323_ = _322_ | _319_;
  assign _324_ = \mem[3] [7] & ~(_093_);
  assign _325_ = \mem[2] [7] & ~(_094_);
  assign _326_ = _325_ | _324_;
  assign _327_ = \mem[1] [7] & ~(_092_);
  assign _328_ = _327_ | _326_;
  assign _329_ = _328_ | _323_;
  assign _330_ = _329_ | _316_;
  assign _345_[7] = _098_ ? \mem[0] [7] : _330_;
  assign _331_ = _038_ & _030_;
  assign _342_[1] = ~_331_;
  assign _332_ = _040_ ^ wbin[2];
  assign _342_[2] = ~_332_;
  assign _333_ = wbin[2] & ~(_040_);
  assign _334_ = ~(_333_ ^ wbin[3]);
  assign _342_[3] = ~_334_;
  assign _335_ = ~(_051_ ^ wptr_gray[4]);
  assign _342_[4] = ~_335_;
  assign _336_ = _068_ & _065_;
  assign _344_[1] = ~_336_;
  assign _337_ = ~(_062_ ^ rbin[2]);
  assign _344_[2] = ~_337_;
  assign _338_ = _062_ & rbin[2];
  assign _339_ = ~(_338_ ^ rbin[3]);
  assign _344_[3] = ~_339_;
  assign _340_ = _064_ ^ rptr_gray[4];
  assign _344_[4] = ~_340_;
  assign _020_ = _336_ ^ rbin[0];
  assign _021_ = _337_ ^ _336_;
  assign _022_ = _339_ ^ _337_;
  assign _023_ = _340_ ^ _339_;
  assign _016_ = _331_ ^ wbin[0];
  assign _017_ = _332_ ^ _331_;
  assign _018_ = _334_ ^ _332_;
  assign _019_ = _335_ ^ _334_;
  always @(posedge rclk)
    if (rrst_n) wptr_sync1[0] <= wptr_gray[0];
  always @(posedge rclk)
    if (rrst_n) wptr_sync1[1] <= wptr_gray[1];
  always @(posedge rclk)
    if (rrst_n) wptr_sync1[2] <= wptr_gray[2];
  always @(posedge rclk)
    if (rrst_n) wptr_sync1[3] <= wptr_gray[3];
  always @(posedge rclk)
    if (rrst_n) wptr_sync1[4] <= wptr_gray[4];
  always @(posedge rclk)
    if (rrst_n) wptr_sync2[0] <= wptr_sync1[0];
  always @(posedge rclk)
    if (rrst_n) wptr_sync2[1] <= wptr_sync1[1];
  always @(posedge rclk)
    if (rrst_n) wptr_sync2[2] <= wptr_sync1[2];
  always @(posedge rclk)
    if (rrst_n) wptr_sync2[3] <= wptr_sync1[3];
  always @(posedge rclk)
    if (rrst_n) wptr_sync2[4] <= wptr_sync1[4];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[0] <= 1'h0;
    else if (_025_) rdata[0] <= _345_[0];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[1] <= 1'h0;
    else if (_025_) rdata[1] <= _345_[1];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[2] <= 1'h0;
    else if (_025_) rdata[2] <= _345_[2];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[3] <= 1'h0;
    else if (_025_) rdata[3] <= _345_[3];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[4] <= 1'h0;
    else if (_025_) rdata[4] <= _345_[4];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[5] <= 1'h0;
    else if (_025_) rdata[5] <= _345_[5];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[6] <= 1'h0;
    else if (_025_) rdata[6] <= _345_[6];
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rdata[7] <= 1'h0;
    else if (_025_) rdata[7] <= _345_[7];
  reg \rbin_reg[0] ;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) \rbin_reg[0]  <= 1'h0;
    else if (_025_) \rbin_reg[0]  <= _343_[0];
  assign rbin[0] = \rbin_reg[0] ;
  reg \rbin_reg[1] ;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) \rbin_reg[1]  <= 1'h0;
    else if (_025_) \rbin_reg[1]  <= _344_[1];
  assign rbin[1] = \rbin_reg[1] ;
  reg \rbin_reg[2] ;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) \rbin_reg[2]  <= 1'h0;
    else if (_025_) \rbin_reg[2]  <= _344_[2];
  assign rbin[2] = \rbin_reg[2] ;
  reg \rbin_reg[3] ;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) \rbin_reg[3]  <= 1'h0;
    else if (_025_) \rbin_reg[3]  <= _344_[3];
  assign rbin[3] = \rbin_reg[3] ;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rptr_gray[0] <= 1'h0;
    else if (_025_) rptr_gray[0] <= _020_;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rptr_gray[1] <= 1'h0;
    else if (_025_) rptr_gray[1] <= _021_;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rptr_gray[2] <= 1'h0;
    else if (_025_) rptr_gray[2] <= _022_;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rptr_gray[3] <= 1'h0;
    else if (_025_) rptr_gray[3] <= _023_;
  always @(posedge rclk, negedge rrst_n)
    if (!rrst_n) rptr_gray[4] <= 1'h0;
    else if (_025_) rptr_gray[4] <= _344_[4];
  reg \wbin_reg[0] ;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) \wbin_reg[0]  <= 1'h0;
    else if (_024_) \wbin_reg[0]  <= _341_[0];
  assign wbin[0] = \wbin_reg[0] ;
  reg \wbin_reg[1] ;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) \wbin_reg[1]  <= 1'h0;
    else if (_024_) \wbin_reg[1]  <= _342_[1];
  assign wbin[1] = \wbin_reg[1] ;
  reg \wbin_reg[2] ;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) \wbin_reg[2]  <= 1'h0;
    else if (_024_) \wbin_reg[2]  <= _342_[2];
  assign wbin[2] = \wbin_reg[2] ;
  reg \wbin_reg[3] ;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) \wbin_reg[3]  <= 1'h0;
    else if (_024_) \wbin_reg[3]  <= _342_[3];
  assign wbin[3] = \wbin_reg[3] ;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) wptr_gray[0] <= 1'h0;
    else if (_024_) wptr_gray[0] <= _016_;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) wptr_gray[1] <= 1'h0;
    else if (_024_) wptr_gray[1] <= _017_;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) wptr_gray[2] <= 1'h0;
    else if (_024_) wptr_gray[2] <= _018_;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) wptr_gray[3] <= 1'h0;
    else if (_024_) wptr_gray[3] <= _019_;
  always @(posedge wclk, negedge wrst_n)
    if (!wrst_n) wptr_gray[4] <= 1'h0;
    else if (_024_) wptr_gray[4] <= _342_[4];
  always @(posedge wclk)
    if (_015_) \mem[0] [0] <= wdata[0];
  always @(posedge wclk)
    if (_015_) \mem[0] [1] <= wdata[1];
  always @(posedge wclk)
    if (_015_) \mem[0] [2] <= wdata[2];
  always @(posedge wclk)
    if (_015_) \mem[0] [3] <= wdata[3];
  always @(posedge wclk)
    if (_015_) \mem[0] [4] <= wdata[4];
  always @(posedge wclk)
    if (_015_) \mem[0] [5] <= wdata[5];
  always @(posedge wclk)
    if (_015_) \mem[0] [6] <= wdata[6];
  always @(posedge wclk)
    if (_015_) \mem[0] [7] <= wdata[7];
  always @(posedge wclk)
    if (_014_) \mem[1] [0] <= wdata[0];
  always @(posedge wclk)
    if (_014_) \mem[1] [1] <= wdata[1];
  always @(posedge wclk)
    if (_014_) \mem[1] [2] <= wdata[2];
  always @(posedge wclk)
    if (_014_) \mem[1] [3] <= wdata[3];
  always @(posedge wclk)
    if (_014_) \mem[1] [4] <= wdata[4];
  always @(posedge wclk)
    if (_014_) \mem[1] [5] <= wdata[5];
  always @(posedge wclk)
    if (_014_) \mem[1] [6] <= wdata[6];
  always @(posedge wclk)
    if (_014_) \mem[1] [7] <= wdata[7];
  always @(posedge wclk)
    if (_013_) \mem[2] [0] <= wdata[0];
  always @(posedge wclk)
    if (_013_) \mem[2] [1] <= wdata[1];
  always @(posedge wclk)
    if (_013_) \mem[2] [2] <= wdata[2];
  always @(posedge wclk)
    if (_013_) \mem[2] [3] <= wdata[3];
  always @(posedge wclk)
    if (_013_) \mem[2] [4] <= wdata[4];
  always @(posedge wclk)
    if (_013_) \mem[2] [5] <= wdata[5];
  always @(posedge wclk)
    if (_013_) \mem[2] [6] <= wdata[6];
  always @(posedge wclk)
    if (_013_) \mem[2] [7] <= wdata[7];
  always @(posedge wclk)
    if (_012_) \mem[3] [0] <= wdata[0];
  always @(posedge wclk)
    if (_012_) \mem[3] [1] <= wdata[1];
  always @(posedge wclk)
    if (_012_) \mem[3] [2] <= wdata[2];
  always @(posedge wclk)
    if (_012_) \mem[3] [3] <= wdata[3];
  always @(posedge wclk)
    if (_012_) \mem[3] [4] <= wdata[4];
  always @(posedge wclk)
    if (_012_) \mem[3] [5] <= wdata[5];
  always @(posedge wclk)
    if (_012_) \mem[3] [6] <= wdata[6];
  always @(posedge wclk)
    if (_012_) \mem[3] [7] <= wdata[7];
  always @(posedge wclk)
    if (_011_) \mem[4] [0] <= wdata[0];
  always @(posedge wclk)
    if (_011_) \mem[4] [1] <= wdata[1];
  always @(posedge wclk)
    if (_011_) \mem[4] [2] <= wdata[2];
  always @(posedge wclk)
    if (_011_) \mem[4] [3] <= wdata[3];
  always @(posedge wclk)
    if (_011_) \mem[4] [4] <= wdata[4];
  always @(posedge wclk)
    if (_011_) \mem[4] [5] <= wdata[5];
  always @(posedge wclk)
    if (_011_) \mem[4] [6] <= wdata[6];
  always @(posedge wclk)
    if (_011_) \mem[4] [7] <= wdata[7];
  always @(posedge wclk)
    if (_010_) \mem[5] [0] <= wdata[0];
  always @(posedge wclk)
    if (_010_) \mem[5] [1] <= wdata[1];
  always @(posedge wclk)
    if (_010_) \mem[5] [2] <= wdata[2];
  always @(posedge wclk)
    if (_010_) \mem[5] [3] <= wdata[3];
  always @(posedge wclk)
    if (_010_) \mem[5] [4] <= wdata[4];
  always @(posedge wclk)
    if (_010_) \mem[5] [5] <= wdata[5];
  always @(posedge wclk)
    if (_010_) \mem[5] [6] <= wdata[6];
  always @(posedge wclk)
    if (_010_) \mem[5] [7] <= wdata[7];
  always @(posedge wclk)
    if (_009_) \mem[6] [0] <= wdata[0];
  always @(posedge wclk)
    if (_009_) \mem[6] [1] <= wdata[1];
  always @(posedge wclk)
    if (_009_) \mem[6] [2] <= wdata[2];
  always @(posedge wclk)
    if (_009_) \mem[6] [3] <= wdata[3];
  always @(posedge wclk)
    if (_009_) \mem[6] [4] <= wdata[4];
  always @(posedge wclk)
    if (_009_) \mem[6] [5] <= wdata[5];
  always @(posedge wclk)
    if (_009_) \mem[6] [6] <= wdata[6];
  always @(posedge wclk)
    if (_009_) \mem[6] [7] <= wdata[7];
  always @(posedge wclk)
    if (_008_) \mem[7] [0] <= wdata[0];
  always @(posedge wclk)
    if (_008_) \mem[7] [1] <= wdata[1];
  always @(posedge wclk)
    if (_008_) \mem[7] [2] <= wdata[2];
  always @(posedge wclk)
    if (_008_) \mem[7] [3] <= wdata[3];
  always @(posedge wclk)
    if (_008_) \mem[7] [4] <= wdata[4];
  always @(posedge wclk)
    if (_008_) \mem[7] [5] <= wdata[5];
  always @(posedge wclk)
    if (_008_) \mem[7] [6] <= wdata[6];
  always @(posedge wclk)
    if (_008_) \mem[7] [7] <= wdata[7];
  always @(posedge wclk)
    if (_007_) \mem[8] [0] <= wdata[0];
  always @(posedge wclk)
    if (_007_) \mem[8] [1] <= wdata[1];
  always @(posedge wclk)
    if (_007_) \mem[8] [2] <= wdata[2];
  always @(posedge wclk)
    if (_007_) \mem[8] [3] <= wdata[3];
  always @(posedge wclk)
    if (_007_) \mem[8] [4] <= wdata[4];
  always @(posedge wclk)
    if (_007_) \mem[8] [5] <= wdata[5];
  always @(posedge wclk)
    if (_007_) \mem[8] [6] <= wdata[6];
  always @(posedge wclk)
    if (_007_) \mem[8] [7] <= wdata[7];
  always @(posedge wclk)
    if (_006_) \mem[9] [0] <= wdata[0];
  always @(posedge wclk)
    if (_006_) \mem[9] [1] <= wdata[1];
  always @(posedge wclk)
    if (_006_) \mem[9] [2] <= wdata[2];
  always @(posedge wclk)
    if (_006_) \mem[9] [3] <= wdata[3];
  always @(posedge wclk)
    if (_006_) \mem[9] [4] <= wdata[4];
  always @(posedge wclk)
    if (_006_) \mem[9] [5] <= wdata[5];
  always @(posedge wclk)
    if (_006_) \mem[9] [6] <= wdata[6];
  always @(posedge wclk)
    if (_006_) \mem[9] [7] <= wdata[7];
  always @(posedge wclk)
    if (_005_) \mem[10] [0] <= wdata[0];
  always @(posedge wclk)
    if (_005_) \mem[10] [1] <= wdata[1];
  always @(posedge wclk)
    if (_005_) \mem[10] [2] <= wdata[2];
  always @(posedge wclk)
    if (_005_) \mem[10] [3] <= wdata[3];
  always @(posedge wclk)
    if (_005_) \mem[10] [4] <= wdata[4];
  always @(posedge wclk)
    if (_005_) \mem[10] [5] <= wdata[5];
  always @(posedge wclk)
    if (_005_) \mem[10] [6] <= wdata[6];
  always @(posedge wclk)
    if (_005_) \mem[10] [7] <= wdata[7];
  always @(posedge wclk)
    if (_004_) \mem[11] [0] <= wdata[0];
  always @(posedge wclk)
    if (_004_) \mem[11] [1] <= wdata[1];
  always @(posedge wclk)
    if (_004_) \mem[11] [2] <= wdata[2];
  always @(posedge wclk)
    if (_004_) \mem[11] [3] <= wdata[3];
  always @(posedge wclk)
    if (_004_) \mem[11] [4] <= wdata[4];
  always @(posedge wclk)
    if (_004_) \mem[11] [5] <= wdata[5];
  always @(posedge wclk)
    if (_004_) \mem[11] [6] <= wdata[6];
  always @(posedge wclk)
    if (_004_) \mem[11] [7] <= wdata[7];
  always @(posedge wclk)
    if (_003_) \mem[12] [0] <= wdata[0];
  always @(posedge wclk)
    if (_003_) \mem[12] [1] <= wdata[1];
  always @(posedge wclk)
    if (_003_) \mem[12] [2] <= wdata[2];
  always @(posedge wclk)
    if (_003_) \mem[12] [3] <= wdata[3];
  always @(posedge wclk)
    if (_003_) \mem[12] [4] <= wdata[4];
  always @(posedge wclk)
    if (_003_) \mem[12] [5] <= wdata[5];
  always @(posedge wclk)
    if (_003_) \mem[12] [6] <= wdata[6];
  always @(posedge wclk)
    if (_003_) \mem[12] [7] <= wdata[7];
  always @(posedge wclk)
    if (_002_) \mem[13] [0] <= wdata[0];
  always @(posedge wclk)
    if (_002_) \mem[13] [1] <= wdata[1];
  always @(posedge wclk)
    if (_002_) \mem[13] [2] <= wdata[2];
  always @(posedge wclk)
    if (_002_) \mem[13] [3] <= wdata[3];
  always @(posedge wclk)
    if (_002_) \mem[13] [4] <= wdata[4];
  always @(posedge wclk)
    if (_002_) \mem[13] [5] <= wdata[5];
  always @(posedge wclk)
    if (_002_) \mem[13] [6] <= wdata[6];
  always @(posedge wclk)
    if (_002_) \mem[13] [7] <= wdata[7];
  always @(posedge wclk)
    if (_001_) \mem[14] [0] <= wdata[0];
  always @(posedge wclk)
    if (_001_) \mem[14] [1] <= wdata[1];
  always @(posedge wclk)
    if (_001_) \mem[14] [2] <= wdata[2];
  always @(posedge wclk)
    if (_001_) \mem[14] [3] <= wdata[3];
  always @(posedge wclk)
    if (_001_) \mem[14] [4] <= wdata[4];
  always @(posedge wclk)
    if (_001_) \mem[14] [5] <= wdata[5];
  always @(posedge wclk)
    if (_001_) \mem[14] [6] <= wdata[6];
  always @(posedge wclk)
    if (_001_) \mem[14] [7] <= wdata[7];
  always @(posedge wclk)
    if (_000_) \mem[15] [0] <= wdata[0];
  always @(posedge wclk)
    if (_000_) \mem[15] [1] <= wdata[1];
  always @(posedge wclk)
    if (_000_) \mem[15] [2] <= wdata[2];
  always @(posedge wclk)
    if (_000_) \mem[15] [3] <= wdata[3];
  always @(posedge wclk)
    if (_000_) \mem[15] [4] <= wdata[4];
  always @(posedge wclk)
    if (_000_) \mem[15] [5] <= wdata[5];
  always @(posedge wclk)
    if (_000_) \mem[15] [6] <= wdata[6];
  always @(posedge wclk)
    if (_000_) \mem[15] [7] <= wdata[7];
  assign _341_[4:1] = { wptr_gray[4], wbin[3:1] };
  assign _342_[0] = _341_[0];
  assign _343_[4:1] = { rptr_gray[4], rbin[3:1] };
  assign _344_[0] = _343_[0];
  assign raddr = rbin[3:0];
  assign rbin[4] = rptr_gray[4];
  assign rptr_sync1 = 5'h00;
  assign rptr_sync2 = 5'h00;
  assign waddr = wbin[3:0];
  assign wbin[4] = wptr_gray[4];
endmodule
