/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module sync_fifo(clk, rst_n, wr_en, rd_en, din, dout, full, empty, almost_full, almost_empty, count);
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire [3:0] _335_;
  wire [3:0] _336_;
  wire [3:0] _337_;
  wire [3:0] _338_;
  wire [7:0] _339_;
  output almost_empty;
  wire almost_empty;
  output almost_full;
  wire almost_full;
  input clk;
  wire clk;
  output [4:0] count;
  reg [4:0] count;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  reg [7:0] dout;
  output empty;
  wire empty;
  output full;
  wire full;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  input rd_en;
  wire rd_en;
  reg [3:0] rd_ptr;
  input rst_n;
  wire rst_n;
  input wr_en;
  wire wr_en;
  reg [3:0] wr_ptr;
  assign _020_ = ~count[4];
  assign _021_ = count[1] | count[0];
  assign _022_ = count[3] | count[2];
  assign _023_ = _022_ | _021_;
  assign empty = _020_ & ~(_023_);
  assign _001_ = rd_en & ~(empty);
  assign full = count[4] & ~(_023_);
  assign _002_ = wr_en & ~(full);
  assign _335_[0] = ~wr_ptr[0];
  assign _003_ = _002_ ^ _001_;
  assign _024_ = _002_ & rst_n;
  assign _025_ = wr_ptr[1] | wr_ptr[0];
  assign _026_ = wr_ptr[2] | wr_ptr[3];
  assign _027_ = _026_ | _025_;
  assign _019_ = _024_ & ~(_027_);
  assign _028_ = wr_ptr[1] | ~(wr_ptr[0]);
  assign _029_ = _028_ | _026_;
  assign _018_ = _024_ & ~(_029_);
  assign _030_ = wr_ptr[0] | ~(wr_ptr[1]);
  assign _031_ = _030_ | _026_;
  assign _017_ = _024_ & ~(_031_);
  assign _032_ = wr_ptr[1] & wr_ptr[0];
  assign _033_ = _026_ | ~(_032_);
  assign _016_ = _024_ & ~(_033_);
  assign _034_ = wr_ptr[3] | ~(wr_ptr[2]);
  assign _035_ = _034_ | _025_;
  assign _015_ = _024_ & ~(_035_);
  assign _036_ = _034_ | _028_;
  assign _014_ = _024_ & ~(_036_);
  assign _037_ = _034_ | _030_;
  assign _013_ = _024_ & ~(_037_);
  assign _038_ = _034_ | ~(_032_);
  assign _012_ = _024_ & ~(_038_);
  assign _039_ = wr_ptr[2] | ~(wr_ptr[3]);
  assign _040_ = _039_ | _025_;
  assign _011_ = _024_ & ~(_040_);
  assign _041_ = _039_ | _028_;
  assign _010_ = _024_ & ~(_041_);
  assign _042_ = _039_ | _030_;
  assign _009_ = _024_ & ~(_042_);
  assign _043_ = _039_ | ~(_032_);
  assign _008_ = _024_ & ~(_043_);
  assign _044_ = ~(wr_ptr[2] & wr_ptr[3]);
  assign _045_ = _044_ | _025_;
  assign _007_ = _024_ & ~(_045_);
  assign _046_ = _044_ | _028_;
  assign _006_ = _024_ & ~(_046_);
  assign _047_ = count[1] | ~(count[0]);
  assign _048_ = _047_ | _022_;
  assign almost_empty = _020_ & ~(_048_);
  assign _049_ = _044_ | _030_;
  assign _005_ = _024_ & ~(_049_);
  assign _050_ = _044_ | ~(_032_);
  assign _004_ = _024_ & ~(_050_);
  assign _337_[0] = ~rd_ptr[0];
  assign _051_ = count[1] & count[0];
  assign _052_ = ~(count[3] & count[2]);
  assign _053_ = _051_ & ~(_052_);
  assign almost_full = _053_ & ~(count[4]);
  assign _054_ = ~(rd_ptr[2] & rd_ptr[3]);
  assign _055_ = rd_ptr[3] & ~(rd_ptr[2]);
  assign _056_ = _054_ & ~(_055_);
  assign _057_ = rd_ptr[2] & ~(rd_ptr[3]);
  assign _058_ = rd_ptr[1] | ~(rd_ptr[0]);
  assign _059_ = rd_ptr[2] | rd_ptr[3];
  assign _060_ = _059_ | _058_;
  assign _061_ = ~(rd_ptr[1] & rd_ptr[0]);
  assign _062_ = _059_ | _061_;
  assign _063_ = rd_ptr[0] | ~(rd_ptr[1]);
  assign _064_ = _059_ | _063_;
  assign _065_ = ~(_064_ & _062_);
  assign _066_ = _065_ | ~(_060_);
  assign _067_ = _066_ | _057_;
  assign _068_ = _056_ & ~(_067_);
  assign _069_ = _054_ | _061_;
  assign _070_ = \mem[15] [0] & ~(_069_);
  assign _071_ = _063_ | _054_;
  assign _072_ = \mem[14] [0] & ~(_071_);
  assign _073_ = _072_ | _070_;
  assign _074_ = _058_ | _054_;
  assign _075_ = \mem[13] [0] & ~(_074_);
  assign _076_ = rd_ptr[1] | rd_ptr[0];
  assign _077_ = _076_ | _054_;
  assign _078_ = \mem[12] [0] & ~(_077_);
  assign _079_ = _078_ | _075_;
  assign _080_ = _079_ | _073_;
  assign _081_ = rd_ptr[2] | ~(rd_ptr[3]);
  assign _082_ = _081_ | _061_;
  assign _083_ = \mem[11] [0] & ~(_082_);
  assign _084_ = _081_ | _063_;
  assign _085_ = \mem[10] [0] & ~(_084_);
  assign _086_ = _085_ | _083_;
  assign _087_ = _081_ | _058_;
  assign _088_ = \mem[9] [0] & ~(_087_);
  assign _089_ = _081_ | _076_;
  assign _090_ = \mem[8] [0] & ~(_089_);
  assign _091_ = _090_ | _088_;
  assign _092_ = _091_ | _086_;
  assign _093_ = _092_ | _080_;
  assign _094_ = rd_ptr[3] | ~(rd_ptr[2]);
  assign _095_ = _094_ | _061_;
  assign _096_ = \mem[7] [0] & ~(_095_);
  assign _097_ = _094_ | _063_;
  assign _098_ = \mem[6] [0] & ~(_097_);
  assign _099_ = _098_ | _096_;
  assign _100_ = _094_ | _058_;
  assign _101_ = \mem[5] [0] & ~(_100_);
  assign _102_ = _094_ | _076_;
  assign _103_ = \mem[4] [0] & ~(_102_);
  assign _104_ = _103_ | _101_;
  assign _105_ = _104_ | _099_;
  assign _106_ = \mem[3] [0] & ~(_062_);
  assign _107_ = \mem[2] [0] & ~(_064_);
  assign _108_ = _107_ | _106_;
  assign _109_ = \mem[1] [0] & ~(_060_);
  assign _110_ = _109_ | _108_;
  assign _111_ = _110_ | _105_;
  assign _112_ = _111_ | _093_;
  assign _339_[0] = _068_ ? \mem[0] [0] : _112_;
  assign _113_ = \mem[15] [1] & ~(_069_);
  assign _114_ = \mem[14] [1] & ~(_071_);
  assign _115_ = _114_ | _113_;
  assign _116_ = \mem[13] [1] & ~(_074_);
  assign _117_ = \mem[12] [1] & ~(_077_);
  assign _118_ = _117_ | _116_;
  assign _119_ = _118_ | _115_;
  assign _120_ = \mem[11] [1] & ~(_082_);
  assign _121_ = \mem[10] [1] & ~(_084_);
  assign _122_ = _121_ | _120_;
  assign _123_ = \mem[9] [1] & ~(_087_);
  assign _124_ = \mem[8] [1] & ~(_089_);
  assign _125_ = _124_ | _123_;
  assign _126_ = _125_ | _122_;
  assign _127_ = _126_ | _119_;
  assign _128_ = \mem[7] [1] & ~(_095_);
  assign _129_ = \mem[6] [1] & ~(_097_);
  assign _130_ = _129_ | _128_;
  assign _131_ = \mem[5] [1] & ~(_100_);
  assign _132_ = \mem[4] [1] & ~(_102_);
  assign _133_ = _132_ | _131_;
  assign _134_ = _133_ | _130_;
  assign _135_ = \mem[3] [1] & ~(_062_);
  assign _136_ = \mem[2] [1] & ~(_064_);
  assign _137_ = _136_ | _135_;
  assign _138_ = \mem[1] [1] & ~(_060_);
  assign _139_ = _138_ | _137_;
  assign _140_ = _139_ | _134_;
  assign _141_ = _140_ | _127_;
  assign _339_[1] = _068_ ? \mem[0] [1] : _141_;
  assign _142_ = \mem[15] [2] & ~(_069_);
  assign _143_ = \mem[14] [2] & ~(_071_);
  assign _144_ = _143_ | _142_;
  assign _145_ = \mem[13] [2] & ~(_074_);
  assign _146_ = \mem[12] [2] & ~(_077_);
  assign _147_ = _146_ | _145_;
  assign _148_ = _147_ | _144_;
  assign _149_ = \mem[11] [2] & ~(_082_);
  assign _150_ = \mem[10] [2] & ~(_084_);
  assign _151_ = _150_ | _149_;
  assign _152_ = \mem[9] [2] & ~(_087_);
  assign _153_ = \mem[8] [2] & ~(_089_);
  assign _154_ = _153_ | _152_;
  assign _155_ = _154_ | _151_;
  assign _156_ = _155_ | _148_;
  assign _157_ = \mem[7] [2] & ~(_095_);
  assign _158_ = \mem[6] [2] & ~(_097_);
  assign _159_ = _158_ | _157_;
  assign _160_ = \mem[5] [2] & ~(_100_);
  assign _161_ = \mem[4] [2] & ~(_102_);
  assign _162_ = _161_ | _160_;
  assign _163_ = _162_ | _159_;
  assign _164_ = \mem[3] [2] & ~(_062_);
  assign _165_ = \mem[2] [2] & ~(_064_);
  assign _166_ = _165_ | _164_;
  assign _167_ = \mem[1] [2] & ~(_060_);
  assign _168_ = _167_ | _166_;
  assign _169_ = _168_ | _163_;
  assign _170_ = _169_ | _156_;
  assign _339_[2] = _068_ ? \mem[0] [2] : _170_;
  assign _171_ = \mem[15] [3] & ~(_069_);
  assign _172_ = \mem[14] [3] & ~(_071_);
  assign _173_ = _172_ | _171_;
  assign _174_ = \mem[13] [3] & ~(_074_);
  assign _175_ = \mem[12] [3] & ~(_077_);
  assign _176_ = _175_ | _174_;
  assign _177_ = _176_ | _173_;
  assign _178_ = \mem[11] [3] & ~(_082_);
  assign _179_ = \mem[10] [3] & ~(_084_);
  assign _180_ = _179_ | _178_;
  assign _181_ = \mem[9] [3] & ~(_087_);
  assign _182_ = \mem[8] [3] & ~(_089_);
  assign _183_ = _182_ | _181_;
  assign _184_ = _183_ | _180_;
  assign _185_ = _184_ | _177_;
  assign _186_ = \mem[7] [3] & ~(_095_);
  assign _187_ = \mem[6] [3] & ~(_097_);
  assign _188_ = _187_ | _186_;
  assign _189_ = \mem[5] [3] & ~(_100_);
  assign _190_ = \mem[4] [3] & ~(_102_);
  assign _191_ = _190_ | _189_;
  assign _192_ = _191_ | _188_;
  assign _193_ = \mem[3] [3] & ~(_062_);
  assign _194_ = \mem[2] [3] & ~(_064_);
  assign _195_ = _194_ | _193_;
  assign _196_ = \mem[1] [3] & ~(_060_);
  assign _197_ = _196_ | _195_;
  assign _198_ = _197_ | _192_;
  assign _199_ = _198_ | _185_;
  assign _339_[3] = _068_ ? \mem[0] [3] : _199_;
  assign _200_ = \mem[15] [4] & ~(_069_);
  assign _201_ = \mem[14] [4] & ~(_071_);
  assign _202_ = _201_ | _200_;
  assign _203_ = \mem[13] [4] & ~(_074_);
  assign _204_ = \mem[12] [4] & ~(_077_);
  assign _205_ = _204_ | _203_;
  assign _206_ = _205_ | _202_;
  assign _207_ = \mem[11] [4] & ~(_082_);
  assign _208_ = \mem[10] [4] & ~(_084_);
  assign _209_ = _208_ | _207_;
  assign _210_ = \mem[9] [4] & ~(_087_);
  assign _211_ = \mem[8] [4] & ~(_089_);
  assign _212_ = _211_ | _210_;
  assign _213_ = _212_ | _209_;
  assign _214_ = _213_ | _206_;
  assign _215_ = \mem[7] [4] & ~(_095_);
  assign _216_ = \mem[6] [4] & ~(_097_);
  assign _217_ = _216_ | _215_;
  assign _218_ = \mem[5] [4] & ~(_100_);
  assign _219_ = \mem[4] [4] & ~(_102_);
  assign _220_ = _219_ | _218_;
  assign _221_ = _220_ | _217_;
  assign _222_ = \mem[3] [4] & ~(_062_);
  assign _223_ = \mem[2] [4] & ~(_064_);
  assign _224_ = _223_ | _222_;
  assign _225_ = \mem[1] [4] & ~(_060_);
  assign _226_ = _225_ | _224_;
  assign _227_ = _226_ | _221_;
  assign _228_ = _227_ | _214_;
  assign _339_[4] = _068_ ? \mem[0] [4] : _228_;
  assign _229_ = \mem[15] [5] & ~(_069_);
  assign _230_ = \mem[14] [5] & ~(_071_);
  assign _231_ = _230_ | _229_;
  assign _232_ = \mem[13] [5] & ~(_074_);
  assign _233_ = \mem[12] [5] & ~(_077_);
  assign _234_ = _233_ | _232_;
  assign _235_ = _234_ | _231_;
  assign _236_ = \mem[11] [5] & ~(_082_);
  assign _237_ = \mem[10] [5] & ~(_084_);
  assign _238_ = _237_ | _236_;
  assign _239_ = \mem[9] [5] & ~(_087_);
  assign _240_ = \mem[8] [5] & ~(_089_);
  assign _241_ = _240_ | _239_;
  assign _242_ = _241_ | _238_;
  assign _243_ = _242_ | _235_;
  assign _244_ = \mem[7] [5] & ~(_095_);
  assign _245_ = \mem[6] [5] & ~(_097_);
  assign _246_ = _245_ | _244_;
  assign _247_ = \mem[5] [5] & ~(_100_);
  assign _248_ = \mem[4] [5] & ~(_102_);
  assign _249_ = _248_ | _247_;
  assign _250_ = _249_ | _246_;
  assign _251_ = \mem[3] [5] & ~(_062_);
  assign _252_ = \mem[2] [5] & ~(_064_);
  assign _253_ = _252_ | _251_;
  assign _254_ = \mem[1] [5] & ~(_060_);
  assign _255_ = _254_ | _253_;
  assign _256_ = _255_ | _250_;
  assign _257_ = _256_ | _243_;
  assign _339_[5] = _068_ ? \mem[0] [5] : _257_;
  assign _258_ = \mem[15] [6] & ~(_069_);
  assign _259_ = \mem[14] [6] & ~(_071_);
  assign _260_ = _259_ | _258_;
  assign _261_ = \mem[13] [6] & ~(_074_);
  assign _262_ = \mem[12] [6] & ~(_077_);
  assign _263_ = _262_ | _261_;
  assign _264_ = _263_ | _260_;
  assign _265_ = \mem[11] [6] & ~(_082_);
  assign _266_ = \mem[10] [6] & ~(_084_);
  assign _267_ = _266_ | _265_;
  assign _268_ = \mem[9] [6] & ~(_087_);
  assign _269_ = \mem[8] [6] & ~(_089_);
  assign _270_ = _269_ | _268_;
  assign _271_ = _270_ | _267_;
  assign _272_ = _271_ | _264_;
  assign _273_ = \mem[7] [6] & ~(_095_);
  assign _274_ = \mem[6] [6] & ~(_097_);
  assign _275_ = _274_ | _273_;
  assign _276_ = \mem[5] [6] & ~(_100_);
  assign _277_ = \mem[4] [6] & ~(_102_);
  assign _278_ = _277_ | _276_;
  assign _279_ = _278_ | _275_;
  assign _280_ = \mem[3] [6] & ~(_062_);
  assign _281_ = \mem[2] [6] & ~(_064_);
  assign _282_ = _281_ | _280_;
  assign _283_ = \mem[1] [6] & ~(_060_);
  assign _284_ = _283_ | _282_;
  assign _285_ = _284_ | _279_;
  assign _286_ = _285_ | _272_;
  assign _339_[6] = _068_ ? \mem[0] [6] : _286_;
  assign _287_ = \mem[15] [7] & ~(_069_);
  assign _288_ = \mem[14] [7] & ~(_071_);
  assign _289_ = _288_ | _287_;
  assign _290_ = \mem[13] [7] & ~(_074_);
  assign _291_ = \mem[12] [7] & ~(_077_);
  assign _292_ = _291_ | _290_;
  assign _293_ = _292_ | _289_;
  assign _294_ = \mem[11] [7] & ~(_082_);
  assign _295_ = \mem[10] [7] & ~(_084_);
  assign _296_ = _295_ | _294_;
  assign _297_ = \mem[9] [7] & ~(_087_);
  assign _298_ = \mem[8] [7] & ~(_089_);
  assign _299_ = _298_ | _297_;
  assign _300_ = _299_ | _296_;
  assign _301_ = _300_ | _293_;
  assign _302_ = \mem[7] [7] & ~(_095_);
  assign _303_ = \mem[6] [7] & ~(_097_);
  assign _304_ = _303_ | _302_;
  assign _305_ = \mem[5] [7] & ~(_100_);
  assign _306_ = \mem[4] [7] & ~(_102_);
  assign _307_ = _306_ | _305_;
  assign _308_ = _307_ | _304_;
  assign _309_ = \mem[3] [7] & ~(_062_);
  assign _310_ = \mem[2] [7] & ~(_064_);
  assign _311_ = _310_ | _309_;
  assign _312_ = \mem[1] [7] & ~(_060_);
  assign _313_ = _312_ | _311_;
  assign _314_ = _313_ | _308_;
  assign _315_ = _314_ | _301_;
  assign _339_[7] = _068_ ? \mem[0] [7] : _315_;
  assign _316_ = _001_ & ~(_002_);
  assign _317_ = _316_ & ~(count[0]);
  assign _318_ = ~(_316_ | count[0]);
  assign _000_[0] = _318_ | _317_;
  assign _319_ = _051_ | ~(_021_);
  assign _320_ = count[1] ^ count[0];
  assign _000_[1] = _316_ ? _319_ : _320_;
  assign _321_ = ~(count[1] | count[0]);
  assign _322_ = _321_ ^ count[2];
  assign _323_ = _051_ ^ count[2];
  assign _000_[2] = _316_ ? _322_ : _323_;
  assign _324_ = _321_ & ~(count[2]);
  assign _325_ = _324_ ^ count[3];
  assign _326_ = _051_ & count[2];
  assign _327_ = _326_ ^ count[3];
  assign _000_[3] = _316_ ? _325_ : _327_;
  assign _328_ = ~(count[3] | count[2]);
  assign _329_ = ~(_321_ | _022_);
  assign _330_ = _328_ & ~(_329_);
  assign _331_ = _330_ ^ count[4];
  assign _332_ = _053_ ^ count[4];
  assign _000_[4] = _316_ ? _331_ : _332_;
  assign _338_[1] = ~(_058_ & _063_);
  assign _338_[2] = ~(_061_ ^ rd_ptr[2]);
  assign _333_ = rd_ptr[2] & ~(_061_);
  assign _338_[3] = _333_ ^ rd_ptr[3];
  assign _336_[1] = ~(_030_ & _028_);
  assign _336_[2] = _032_ ^ wr_ptr[2];
  assign _334_ = _032_ & wr_ptr[2];
  assign _336_[3] = _334_ ^ wr_ptr[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[0] <= 1'h0;
    else if (_003_) count[0] <= _000_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[1] <= 1'h0;
    else if (_003_) count[1] <= _000_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[2] <= 1'h0;
    else if (_003_) count[2] <= _000_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[3] <= 1'h0;
    else if (_003_) count[3] <= _000_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[4] <= 1'h0;
    else if (_003_) count[4] <= _000_[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[0] <= 1'h0;
    else if (_001_) dout[0] <= _339_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[1] <= 1'h0;
    else if (_001_) dout[1] <= _339_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[2] <= 1'h0;
    else if (_001_) dout[2] <= _339_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[3] <= 1'h0;
    else if (_001_) dout[3] <= _339_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[4] <= 1'h0;
    else if (_001_) dout[4] <= _339_[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[5] <= 1'h0;
    else if (_001_) dout[5] <= _339_[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[6] <= 1'h0;
    else if (_001_) dout[6] <= _339_[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[7] <= 1'h0;
    else if (_001_) dout[7] <= _339_[7];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rd_ptr[0] <= 1'h0;
    else if (_001_) rd_ptr[0] <= _337_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rd_ptr[1] <= 1'h0;
    else if (_001_) rd_ptr[1] <= _338_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rd_ptr[2] <= 1'h0;
    else if (_001_) rd_ptr[2] <= _338_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rd_ptr[3] <= 1'h0;
    else if (_001_) rd_ptr[3] <= _338_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wr_ptr[0] <= 1'h0;
    else if (_002_) wr_ptr[0] <= _335_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wr_ptr[1] <= 1'h0;
    else if (_002_) wr_ptr[1] <= _336_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wr_ptr[2] <= 1'h0;
    else if (_002_) wr_ptr[2] <= _336_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wr_ptr[3] <= 1'h0;
    else if (_002_) wr_ptr[3] <= _336_[3];
  always @(posedge clk)
    if (_019_) \mem[0] [0] <= din[0];
  always @(posedge clk)
    if (_019_) \mem[0] [1] <= din[1];
  always @(posedge clk)
    if (_019_) \mem[0] [2] <= din[2];
  always @(posedge clk)
    if (_019_) \mem[0] [3] <= din[3];
  always @(posedge clk)
    if (_019_) \mem[0] [4] <= din[4];
  always @(posedge clk)
    if (_019_) \mem[0] [5] <= din[5];
  always @(posedge clk)
    if (_019_) \mem[0] [6] <= din[6];
  always @(posedge clk)
    if (_019_) \mem[0] [7] <= din[7];
  always @(posedge clk)
    if (_018_) \mem[1] [0] <= din[0];
  always @(posedge clk)
    if (_018_) \mem[1] [1] <= din[1];
  always @(posedge clk)
    if (_018_) \mem[1] [2] <= din[2];
  always @(posedge clk)
    if (_018_) \mem[1] [3] <= din[3];
  always @(posedge clk)
    if (_018_) \mem[1] [4] <= din[4];
  always @(posedge clk)
    if (_018_) \mem[1] [5] <= din[5];
  always @(posedge clk)
    if (_018_) \mem[1] [6] <= din[6];
  always @(posedge clk)
    if (_018_) \mem[1] [7] <= din[7];
  always @(posedge clk)
    if (_017_) \mem[2] [0] <= din[0];
  always @(posedge clk)
    if (_017_) \mem[2] [1] <= din[1];
  always @(posedge clk)
    if (_017_) \mem[2] [2] <= din[2];
  always @(posedge clk)
    if (_017_) \mem[2] [3] <= din[3];
  always @(posedge clk)
    if (_017_) \mem[2] [4] <= din[4];
  always @(posedge clk)
    if (_017_) \mem[2] [5] <= din[5];
  always @(posedge clk)
    if (_017_) \mem[2] [6] <= din[6];
  always @(posedge clk)
    if (_017_) \mem[2] [7] <= din[7];
  always @(posedge clk)
    if (_016_) \mem[3] [0] <= din[0];
  always @(posedge clk)
    if (_016_) \mem[3] [1] <= din[1];
  always @(posedge clk)
    if (_016_) \mem[3] [2] <= din[2];
  always @(posedge clk)
    if (_016_) \mem[3] [3] <= din[3];
  always @(posedge clk)
    if (_016_) \mem[3] [4] <= din[4];
  always @(posedge clk)
    if (_016_) \mem[3] [5] <= din[5];
  always @(posedge clk)
    if (_016_) \mem[3] [6] <= din[6];
  always @(posedge clk)
    if (_016_) \mem[3] [7] <= din[7];
  always @(posedge clk)
    if (_015_) \mem[4] [0] <= din[0];
  always @(posedge clk)
    if (_015_) \mem[4] [1] <= din[1];
  always @(posedge clk)
    if (_015_) \mem[4] [2] <= din[2];
  always @(posedge clk)
    if (_015_) \mem[4] [3] <= din[3];
  always @(posedge clk)
    if (_015_) \mem[4] [4] <= din[4];
  always @(posedge clk)
    if (_015_) \mem[4] [5] <= din[5];
  always @(posedge clk)
    if (_015_) \mem[4] [6] <= din[6];
  always @(posedge clk)
    if (_015_) \mem[4] [7] <= din[7];
  always @(posedge clk)
    if (_014_) \mem[5] [0] <= din[0];
  always @(posedge clk)
    if (_014_) \mem[5] [1] <= din[1];
  always @(posedge clk)
    if (_014_) \mem[5] [2] <= din[2];
  always @(posedge clk)
    if (_014_) \mem[5] [3] <= din[3];
  always @(posedge clk)
    if (_014_) \mem[5] [4] <= din[4];
  always @(posedge clk)
    if (_014_) \mem[5] [5] <= din[5];
  always @(posedge clk)
    if (_014_) \mem[5] [6] <= din[6];
  always @(posedge clk)
    if (_014_) \mem[5] [7] <= din[7];
  always @(posedge clk)
    if (_013_) \mem[6] [0] <= din[0];
  always @(posedge clk)
    if (_013_) \mem[6] [1] <= din[1];
  always @(posedge clk)
    if (_013_) \mem[6] [2] <= din[2];
  always @(posedge clk)
    if (_013_) \mem[6] [3] <= din[3];
  always @(posedge clk)
    if (_013_) \mem[6] [4] <= din[4];
  always @(posedge clk)
    if (_013_) \mem[6] [5] <= din[5];
  always @(posedge clk)
    if (_013_) \mem[6] [6] <= din[6];
  always @(posedge clk)
    if (_013_) \mem[6] [7] <= din[7];
  always @(posedge clk)
    if (_012_) \mem[7] [0] <= din[0];
  always @(posedge clk)
    if (_012_) \mem[7] [1] <= din[1];
  always @(posedge clk)
    if (_012_) \mem[7] [2] <= din[2];
  always @(posedge clk)
    if (_012_) \mem[7] [3] <= din[3];
  always @(posedge clk)
    if (_012_) \mem[7] [4] <= din[4];
  always @(posedge clk)
    if (_012_) \mem[7] [5] <= din[5];
  always @(posedge clk)
    if (_012_) \mem[7] [6] <= din[6];
  always @(posedge clk)
    if (_012_) \mem[7] [7] <= din[7];
  always @(posedge clk)
    if (_011_) \mem[8] [0] <= din[0];
  always @(posedge clk)
    if (_011_) \mem[8] [1] <= din[1];
  always @(posedge clk)
    if (_011_) \mem[8] [2] <= din[2];
  always @(posedge clk)
    if (_011_) \mem[8] [3] <= din[3];
  always @(posedge clk)
    if (_011_) \mem[8] [4] <= din[4];
  always @(posedge clk)
    if (_011_) \mem[8] [5] <= din[5];
  always @(posedge clk)
    if (_011_) \mem[8] [6] <= din[6];
  always @(posedge clk)
    if (_011_) \mem[8] [7] <= din[7];
  always @(posedge clk)
    if (_010_) \mem[9] [0] <= din[0];
  always @(posedge clk)
    if (_010_) \mem[9] [1] <= din[1];
  always @(posedge clk)
    if (_010_) \mem[9] [2] <= din[2];
  always @(posedge clk)
    if (_010_) \mem[9] [3] <= din[3];
  always @(posedge clk)
    if (_010_) \mem[9] [4] <= din[4];
  always @(posedge clk)
    if (_010_) \mem[9] [5] <= din[5];
  always @(posedge clk)
    if (_010_) \mem[9] [6] <= din[6];
  always @(posedge clk)
    if (_010_) \mem[9] [7] <= din[7];
  always @(posedge clk)
    if (_009_) \mem[10] [0] <= din[0];
  always @(posedge clk)
    if (_009_) \mem[10] [1] <= din[1];
  always @(posedge clk)
    if (_009_) \mem[10] [2] <= din[2];
  always @(posedge clk)
    if (_009_) \mem[10] [3] <= din[3];
  always @(posedge clk)
    if (_009_) \mem[10] [4] <= din[4];
  always @(posedge clk)
    if (_009_) \mem[10] [5] <= din[5];
  always @(posedge clk)
    if (_009_) \mem[10] [6] <= din[6];
  always @(posedge clk)
    if (_009_) \mem[10] [7] <= din[7];
  always @(posedge clk)
    if (_008_) \mem[11] [0] <= din[0];
  always @(posedge clk)
    if (_008_) \mem[11] [1] <= din[1];
  always @(posedge clk)
    if (_008_) \mem[11] [2] <= din[2];
  always @(posedge clk)
    if (_008_) \mem[11] [3] <= din[3];
  always @(posedge clk)
    if (_008_) \mem[11] [4] <= din[4];
  always @(posedge clk)
    if (_008_) \mem[11] [5] <= din[5];
  always @(posedge clk)
    if (_008_) \mem[11] [6] <= din[6];
  always @(posedge clk)
    if (_008_) \mem[11] [7] <= din[7];
  always @(posedge clk)
    if (_007_) \mem[12] [0] <= din[0];
  always @(posedge clk)
    if (_007_) \mem[12] [1] <= din[1];
  always @(posedge clk)
    if (_007_) \mem[12] [2] <= din[2];
  always @(posedge clk)
    if (_007_) \mem[12] [3] <= din[3];
  always @(posedge clk)
    if (_007_) \mem[12] [4] <= din[4];
  always @(posedge clk)
    if (_007_) \mem[12] [5] <= din[5];
  always @(posedge clk)
    if (_007_) \mem[12] [6] <= din[6];
  always @(posedge clk)
    if (_007_) \mem[12] [7] <= din[7];
  always @(posedge clk)
    if (_006_) \mem[13] [0] <= din[0];
  always @(posedge clk)
    if (_006_) \mem[13] [1] <= din[1];
  always @(posedge clk)
    if (_006_) \mem[13] [2] <= din[2];
  always @(posedge clk)
    if (_006_) \mem[13] [3] <= din[3];
  always @(posedge clk)
    if (_006_) \mem[13] [4] <= din[4];
  always @(posedge clk)
    if (_006_) \mem[13] [5] <= din[5];
  always @(posedge clk)
    if (_006_) \mem[13] [6] <= din[6];
  always @(posedge clk)
    if (_006_) \mem[13] [7] <= din[7];
  always @(posedge clk)
    if (_005_) \mem[14] [0] <= din[0];
  always @(posedge clk)
    if (_005_) \mem[14] [1] <= din[1];
  always @(posedge clk)
    if (_005_) \mem[14] [2] <= din[2];
  always @(posedge clk)
    if (_005_) \mem[14] [3] <= din[3];
  always @(posedge clk)
    if (_005_) \mem[14] [4] <= din[4];
  always @(posedge clk)
    if (_005_) \mem[14] [5] <= din[5];
  always @(posedge clk)
    if (_005_) \mem[14] [6] <= din[6];
  always @(posedge clk)
    if (_005_) \mem[14] [7] <= din[7];
  always @(posedge clk)
    if (_004_) \mem[15] [0] <= din[0];
  always @(posedge clk)
    if (_004_) \mem[15] [1] <= din[1];
  always @(posedge clk)
    if (_004_) \mem[15] [2] <= din[2];
  always @(posedge clk)
    if (_004_) \mem[15] [3] <= din[3];
  always @(posedge clk)
    if (_004_) \mem[15] [4] <= din[4];
  always @(posedge clk)
    if (_004_) \mem[15] [5] <= din[5];
  always @(posedge clk)
    if (_004_) \mem[15] [6] <= din[6];
  always @(posedge clk)
    if (_004_) \mem[15] [7] <= din[7];
  assign _335_[3:1] = wr_ptr[3:1];
  assign _336_[0] = _335_[0];
  assign _337_[3:1] = rd_ptr[3:1];
  assign _338_[0] = _337_[0];
endmodule
